#ifndef _AQ2_PRM_USER
#define _AQ2_PRM_USER

// Device indexes for CORHW_DEVICE_PRM_GET_VOLTAGE
#define AQ2_VOLTAGE_INDEX_12V                0
#define AQ2_VOLTAGE_INDEX_INPUT_THRESHOLD    1
#define AQ2_VOLTAGE_INDEX_FPGA_VCCINT        2
#define AQ2_VOLTAGE_INDEX_FPGA_VCCAUX        3
#define AQ2_VOLTAGE_POCL0_RSENSE             4
#define AQ2_VOLTAGE_POCL1_RSENSE             5

// Device indexes for CORHW_DEVICE_PRM_GET_TEMPERATURE
#define AQ2_TEMPERATURE_INDEX_FPGA     0

// Parameter indexes for CORHW_DEVICE_PRM_GET_LANES_STATS
#define AQ2_CLHS_LANES_CRC_ERROR_COUNT 0
#define AQ2_CLHS_LANES_VIDEO_MSG_COUNT 1
#define AQ2_CLHS_LANES_PACKET_BUFFER_OVERFLOW_COUNT 2
#define AQ2_CLHS_LANES_RESEND_FLAG_COUNT 3
#define AQ2_CLHS_LANES_8B_10B_ERROR_COUNT 4

#endif